### ISSUE TITLE
Internal structure for CG context positions

### ISSUE THREAD

**Issue by mr-martian** [apertium/tree-sitter-apertium#7]
At present `-1**C` is parsed as `(contextpos)`, which is a bit annoying for downstream processing. It would be nice if this could have some internal structure, like maybe `(contextpos (minus) (number) (scan_continue) (careful))`.

**Comment by TinoDidriksen** [comment]
True, but can Tree Sitter handle the myriad of ways a position can be written? `-1**C` == `**-1C` == `**1C-` == `C**1-` ... etc.

**Comment by mr-martian** [comment]
```
minus: $ => "-",
number: $ => /[0-9]+/,
scan_continue: $ => "**",
careful: $ => "C",
contextpos: $ => repeat1(choice($.minus, $.number, $.scan_continue, $.careful)),
```
would handle all of those

**Comment by mr-martian** [comment]
Done in 9b79b03
